// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServer(arg1:main.ServerInfo):Promise<void>;

export function AnalyzeNetworkCapture(arg1:string):Promise<string>;

export function AnalyzeSystemLog(arg1:string):Promise<string>;

export function Ask(arg1:string):Promise<string>;

export function CheckModelExists():Promise<boolean>;

export function DeleteServer(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExecuteOnMultipleServers(arg1:Array<string>,arg2:string):Promise<Record<string, string>>;

export function GetAvailableModels():Promise<Array<main.ModelInfo>>;

export function GetCPUInfo(arg1:string):Promise<string>;

export function GetDiskInfo(arg1:string):Promise<string>;

export function GetLoadedModelPath():Promise<string>;

export function GetLogInfo(arg1:string,arg2:number):Promise<string>;

export function GetMemoryInfo(arg1:string):Promise<string>;

export function GetModelPath():Promise<string>;

export function GetNetworkInfo(arg1:string):Promise<string>;

export function GetProcessInfo(arg1:string):Promise<string>;

export function GetServer(arg1:string):Promise<main.ServerInfo>;

export function GetServerConnectionStatus():Promise<Record<string, boolean>>;

export function GetServers():Promise<Array<main.ServerInfo>>;

export function GetSystemInfo(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsModelLoaded():Promise<boolean>;

export function LoadModel(arg1:string):Promise<void>;

export function RefreshServerConnections():Promise<void>;

export function TestConnection(arg1:main.ServerInfo):Promise<void>;

export function UnloadModel():Promise<void>;

export function UpdateServer(arg1:main.ServerInfo):Promise<void>;
