// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function AnalyzeNetworkCapture(arg1) {
  return window['go']['main']['App']['AnalyzeNetworkCapture'](arg1);
}

export function AnalyzeSystemLog(arg1) {
  return window['go']['main']['App']['AnalyzeSystemLog'](arg1);
}

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function CheckModelExists() {
  return window['go']['main']['App']['CheckModelExists']();
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteOnMultipleServers(arg1, arg2) {
  return window['go']['main']['App']['ExecuteOnMultipleServers'](arg1, arg2);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCPUInfo(arg1) {
  return window['go']['main']['App']['GetCPUInfo'](arg1);
}

export function GetDiskInfo(arg1) {
  return window['go']['main']['App']['GetDiskInfo'](arg1);
}

export function GetLoadedModelPath() {
  return window['go']['main']['App']['GetLoadedModelPath']();
}

export function GetLogInfo(arg1, arg2) {
  return window['go']['main']['App']['GetLogInfo'](arg1, arg2);
}

export function GetMemoryInfo(arg1) {
  return window['go']['main']['App']['GetMemoryInfo'](arg1);
}

export function GetModelPath() {
  return window['go']['main']['App']['GetModelPath']();
}

export function GetNetworkInfo(arg1) {
  return window['go']['main']['App']['GetNetworkInfo'](arg1);
}

export function GetProcessInfo(arg1) {
  return window['go']['main']['App']['GetProcessInfo'](arg1);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServerConnectionStatus() {
  return window['go']['main']['App']['GetServerConnectionStatus']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSystemInfo(arg1) {
  return window['go']['main']['App']['GetSystemInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsModelLoaded() {
  return window['go']['main']['App']['IsModelLoaded']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function RefreshServerConnections() {
  return window['go']['main']['App']['RefreshServerConnections']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UnloadModel() {
  return window['go']['main']['App']['UnloadModel']();
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
